<?php

/**
 * @file
 * Contains smartlabs_doc.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function smartlabs_doc_theme($existing, $type, $theme, $path) {
  return [
    'sldoc_list_title' => [
      'variables' => [
        'text' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function smartlabs_doc_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  switch ($form_id) {
    case 'node_doc_form':
    case 'node_doc_edit_form':

      // Alters "Specific to Location" and "Specific to Company" fields:
      // cannot be used if “Global document” checkbox is checked.
      if (isset($form['field_location'])) {
        $form['field_location']['#states'] = [
          'visible' => [
            'select[name="field_doc_type"]' => ['value' => 'location'],
          ],
        ];
      }
      if (isset($form['field_company'])) {
        $form['field_company']['#states'] = [
          'visible' => [
            'select[name="field_doc_type"]' => ['value' => 'company'],
          ],
        ];
      }

      // Allow either Link URL or Asset Upload, not both.
      $form['field_doc_link_url']['#states'] = [
        'enabled' => [
          'input[name="files[field_doc_file_0]"]' => ['value' => ''],
        ],
      ];
      $form['field_doc_file']['#states'] = [
        'enabled' => [
          'input[name="field_doc_link_url[0][value]"]' => ['value' => ''],
        ],
      ];
      break;

    // After creating a new Section term, go back to the Section list page.
    case 'taxonomy_term_sections_form':
      $user_input = $form_state->getUserInput();
      if (!empty($user_input)) {
        $form['actions']['submit']['#submit'][] = 'smartlabs_doc_sections_form_submit';
      }
      break;
  }

}

/**
 * Custom submit action for Section term form.
 */
function smartlabs_doc_sections_form_submit($form, FormStateInterface &$form_state) {
  global $base_url;
  $response = new Symfony\Component\HttpFoundation\RedirectResponse($base_url . '/admin/structure/taxonomy/manage/sections/overview');
  $response->send();
  return;
}

/**
 * Implements hook_views_query_alter().
 */
function smartlabs_doc_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'docs') {
    if ($view->getDisplay()->display['id'] == 'block_docs') {

      // Move default "Doc type" filter to OR section.
      unset($query->where[0]);
      $query->addWhere(2, 'node__field_doc_type.field_doc_type_value', ['global']);

      // Add a Filter Docs by current User's Company.
      $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
      $company_id = current($user->get('field_user_company')->getValue())['target_id'];
      if (!empty($company_id) && is_numeric($company_id)) {
        $query->addWhere(2, 'node__field_company.field_company_target_id', [(int)$company_id]);
      }
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function smartlabs_doc_element_info_alter(array &$types) {
  if (isset($types['table'])) {
    $types['table']['#attached']['library'][] = 'smartlabs_doc/sl_table';
  }
}
